{
  "database": {
    "host": "localhost",
    "port": 5432,
    "user": "postgres",
    "password": "SENHA",
    "database": "bdAbp"
  },
  "backend": {
    "host": "192.168.15.4",
    "port": 3000
  }
}