database:
  host: shuttle.proxy.rlwy.net # usamos railway
  port: # porta do projeto
  user: postgres
  password: # senha do projeto
  database: bdAbp

backend:
  host: # colocar o IP do localhost aqui
  port: 3000

email:
  host: smtp.gmail.com
  port: 587
  user: innocodesolutions@gmail.com
  pass: https://myaccount.google.com/apppasswords   // acessar o link e gerar a senha de acesso
  
