name: Teste Frontend

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # ou a versão do seu projeto

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes com Jest
        run: npm test
